### ISSUE TITLE
Error when trying to deploy with minio service

### ISSUE THREAD

**Issue by mshadbolt** [CanDIG/CanDIGv2#844]
This issue is from @rjiang9 

## Operating system
- OS (OSX arm)

## What version are you deploying

latest stable

## Step where failure occurred (make-?)

It’s about the miniO deployment on my local computer (Macbook). I tried a few times but still can’t get it working. Here is what I did:

In the .env,

`CANDIG_MODULES=logging………… minio`

I checked out the stable branch of the candig repo, and followed the installation guide and `make test-integration` passed. When I tried to access the MiniO by visiting http://candig.docker.internal:9001/ , it says the site can’t be reached.

I checked the [error.txt](https://github.com/user-attachments/files/17636396/error.txt) , it has:

Output of build-minio:

service "minio" refers to undefined volume minio-data: invalid compose project

Output of compose-minio:

service "minio" refers to undefined volume minio-data: invalid compose project

My questions are:

What did I miss in the deployment process but adding the ‘minio’ into the CANDIG_MODULES in .env? What do I need to do to get it working?
Where can I get the MiniO access key and secret key?

## Are there errors in `tmp/error.txt`?

see attached and above

**Comment by rjiang9** [comment]
[like]  Ray Jiang reacted to your message:
________________________________
From: Marion ***@***.***>
Sent: Tuesday, November 5, 2024 5:39:55 PM
To: CanDIG/CanDIGv2 ***@***.***>
Cc: Ray Jiang ***@***.***>; Mention ***@***.***>
Subject: [CanDIG/CanDIGv2] Error when trying to deploy with minio service (Issue #844)

[△EXTERNAL]



This issue is from @rjiang9<https://github.com/rjiang9>

Operating system

  *   OS (OSX arm)

What version are you deploying

latest stable

Step where failure occurred (make-?)

It’s about the miniO deployment on my local computer (Macbook). I tried a few times but still can’t get it working. Here is what I did:

In the .env,

CANDIG_MODULES=logging………… minio

I checked out the stable branch of the candig repo, and followed the installation guide and make test-integration passed. When I tried to access the MiniO by visiting http://candig.docker.internal:9001/ , it says the site can’t be reached.

I checked the error.txt<https://github.com/user-attachments/files/17636396/error.txt> , it has:

Output of build-minio:

service "minio" refers to undefined volume minio-data: invalid compose project

Output of compose-minio:

service "minio" refers to undefined volume minio-data: invalid compose project

My questions are:

What did I miss in the deployment process but adding the ‘minio’ into the CANDIG_MODULES in .env? What do I need to do to get it working?
Where can I get the MiniO access key and secret key?

Are there errors in tmp/error.txt?

see attached and above

Are there errors in the central log for the affected container(s)? tmp/logs/*.log
Any other information

**Comment by daisieh** [comment]
We don't use minio anymore so haven't checked it in some time. Our example.env has it commented out: 
```
CANDIG_MODULES=logging keycloak vault redis postgres htsget katsu query tyk opa federation candig-ingest candig-data-portal
    #minio drs-server wes-server monitoring
```

I would recommend you remove it from the sequence and don't build it at all.

**Comment by daisieh** [comment]
Why do you want to install minio on your stack? I can spend some time helping you figure out where we commented everything out, but I'm wondering what your use case is.

**Comment by rjiang9** [comment]
> Why do you want to install minio on your stack? I can spend some time helping you figure out where we commented everything out, but I'm wondering what your use case is.

Hi Daisieh, 

We are thinking to use miniO for the Genomic files. What is your suggestion? I still see MiniO related lines in .env files, will they be removed or they are for communicating to separate miniO server?

If I built my own MiniO, what do I need to do for the communication between CanDigv2 and MiniO?

Thanks,
Ray

<img width="511" alt="image" src="https://github.com/user-attachments/assets/ee7567a1-cd64-45df-88e9-f1ee00947ff9">


<img width="900" alt="image" src="https://github.com/user-attachments/assets/bef1252e-039c-48bb-a302-4f5ef85c0930">

**Comment by daisieh** [comment]
You should be able to uncomment a few lines and have it work again:
* in Makefile, line 360, uncomment out #minio-secrets
* in lib/candigv2/docker-compose.yml, uncomment lines 35-41

This should re-enable the creation of the relevant secrets and docker volumes.

I've not tried attaching the minio container to any sort of large-capacity volume, which I'm assuming you'd need if you wanted to use it as an actual genomic data store. You should also look into security and backup features for it to see if it will actually meet your needs.

**Comment by rjiang9** [comment]
Hi @daisieh 



> I've not tried attaching the minio container to any sort of large-capacity volume, which I'm assuming you'd need if you wanted to use it as an actual genomic data store. You should also look into security and backup features for it to see if it will actually meet your needs.

We are still in the testing phase and would like to see how the whole CanDig system looks like.  a working Candig deployment with Minio is perfect in this phase. We will worry about the object store with large capacity later. 

Thanks,
Ray

**Comment by daisieh** [comment]
You'll have to uncomment the lines starting here: https://github.com/CanDIG/CanDIGv2/blob/4382d149a425e049693d1f678bacd2204db6778c/lib/candigv2/docker-compose.yml#L2 and here: https://github.com/CanDIG/CanDIGv2/blob/4382d149a425e049693d1f678bacd2204db6778c/lib/candigv2/docker-compose.yml#L34

**Comment by rjiang9** [comment]
Thank you, @daisieh 

I also uncommented L384 & 385 in Makefile - otherwise minio can't be accessed by http://candig.docker.internal:9001

**Comment by rjiang9** [comment]
This ticket can be closed. Thanks again. @mshadbolt @daisieh
